### ISSUE TITLE
Set iframe width and height?

### ISSUE THREAD

**Issue by g5400658** [oscarotero/Embed#65]
Is it possible to set specific widths and heights for the iframe embed codes?

**Comment by oscarotero** [comment]
No. Some oembed services allows this parameter but others not.
But you can use css to set the width and height of the iframes. [Here's an issue with this](https://github.com/oscarotero/Embed/issues/3#issuecomment-17990699)

And there's the property `aspectRatio` to make the iframes responsive:

```css
.responsive {
  position: relative;
}
.responsive iframe {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
}
```
```html
<div class="responsive" style="padding-bottom: <?= $info->aspectRatio.'%' ?>">
    <?= $info->code ?>
</div>
```
